version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu-latest
    steps:
      - run:
          name: Just Pull the Docker Image
          command: |
            sudo service docker status
            sudo docker images
