version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=1.$CIRCLE_BUILD_NUM
          docker build -t frehman/pipe1:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push frehman/pipe1:$TAG
