version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Build the Docker Image from the Dockerfile
          command: |
            docker build . --tag frehman/pipe1:v.5.55
