version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Installing the Docker Daemon
          command: |
            apt update -y
            apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
            apt update -y
            apt-cache policy docker-ce
            apt install docker-ce -y
            systemctl status docker
            usermod -aG docker ${USER}
            docker
