version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/faisikhan/apache-maven-test/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-first-job:
    environment:
      Build Number: 1
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo This is my first CircleCI Job!

workflows:
  my-custom-workflow:
    jobs:
      - my-first-job