name: Docker Image CI

on:
 push:
   branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo test
       # docker build . --tag frehman/pipe1:v.9.22
      
    - name: Logging into the Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          
    - name: Pushing the Image to Docker Hub
      run: |
        echo test
            #    docker push frehman/pipe1:v.9.22
            #     - name: SSH Authentication with the Deployment Server
#       run: |
#             mkdir -p ~/.ssh/
#             echo "${{secrets.SSH_KEY}}" > ~/.ssh/deploy.pem
#             chmod 600 ~/.ssh/deploy.pem
#             pwd
#             ls -la
    
    - name: Connect with the Deployment Server via SSH
      env:
         host: '20.42.118.179'
         username: 'faisal'
         password: ${{secrets.SSH_PASSWORD}}
      run: |
            sshpass -p "${{env.password}} ssh -o StrictHostKeyChecking=no ${{env.username}}@${{env.host}} "
            echo 'current location'
            pwd
          
#     - name: Login to the Deployment Server and run the Script to Deploy Service.
#       run: |
#        uname -a
#       ssh -i ~/.ssh/deploy.pem -oStrictHostKeyChecking=no frehman@20.42.118.179
#       scp -i ~/.ssh/deploy.pem -oStrictHostKeyChecking=no doscript.sh frehman@20.42.118.179:/home/users/frehman
#      ssh -i ~/.ssh/deploy.pem -oStrictHostKeyChecking=no frehman@54.91.22.158 "echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  && chmod +x doscript.sh && sh doscript.sh"
